# Adapted from Garnet and ButterPHY

name: termination

commands:
  - |
    mkdir -p outputs
    tar -xvf /home/sjkim85/dragonphy_tarballs/termination-latest.tar.gz -C outputs
    mv outputs/termination-0.0.0/* outputs/
outputs:
  - termination.lef
  - termination.gds
  - termination.spi
  - termination.version
